sudo: required
language: node_js
before_install:
 - gem install sass
 - gem install ruby 
 - gem install scss_lint
 - npm -g install npm@latest
before_script:
  - npm install -g gulp
script: gulp travis