init:
  - git config --global core.autocrlf true
# What combinations to test
environment:
  matrix:
    - nodejs_version: "4.2.2"
install:
  - ps: Install-Product node $env:nodejs_version
  - gem install sass
  - gem install ruby 
  - gem install scss_lint
  - npm install -g npm
  - npm install gulp -g
  - npm install    
  - npm install promise
test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # We test multiple Windows shells because of prior stdout buffering issues
  # filed against Grunt. https://github.com/joyent/node/issues/3584  
  - npm test
  - gulp deploy 
build: off
matrix:
  fast_finish: true
cache:
  - node_modules -> package.json